[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "book-to-video"
version = "0.1.0"
authors = [
  { name="Rubén Pozo Molina" },
]
description = "Convert EPUB books into a series of videos for YouTube."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic",
    "tqdm",
    "ebooklib",
    "beautifulsoup4",
    "pyttsx3",
    "moviepy",
    "Pillow",
    "numpy",
]

[project.urls]
"Homepage" = "https://github.com/RubenPozoMolina/book-to-video"
"Bug Tracker" = "https://github.com/RubenPozoMolina/book-to-video/issues"

[project.scripts]
book-to-video = "src.book_to_video:main"
